num_classes: 10
epochs: 60
grad_clip: 5.0
# grad_clip: 1.0
log_frequency: 100

model:
  name: ResNet18CVAE
  num_classes: 10
  stem_end_block: 7
  latent_dim: 256

criterion:
  name: CrossEntropyLoss

optimizer:
  # name: SGD
  # lr: 0.1
  # weight_decay: 5.e-4
  # momentum: 0.9
  name: Adam
  lr: 0.005
  weight_decay: 0.0

scheduler:
  name: CosineAnnealingLR
  T_max: $epochs
  eta_min: 0.0
  # name: ExponentialLR
  # gamma: 0.95

dataset:
  name: DatasetGenerator
  train_batch_size: 128
  eval_batch_size: 128
